# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d5a104810f7829d10e74aaf3417cfa27f3ca37114711f568e798d35f064eb8a65b03c285e771cbbce76b4f8052cdcc78279a477add2c3fddf1aea8486e98d06

test:
  secret_key_base: f921022c8eb543c6e3c9103104804a311fb89f7316e8473ce73a059a78fc0384310e7c1b668c2d36d7a5c965dcf6d6d525d3dd1f5d380f4fa6e2c98610ef2f5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
